// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYzuyqjwl6dKl4oS5_VrqCHlqxuHRdXMI',
    appId: '1:608499304466:web:a390033ba4cd62ba4370cb',
    messagingSenderId: '608499304466',
    projectId: 'lojaagua-v1',
    authDomain: 'lojaagua-v1.firebaseapp.com',
    storageBucket: 'lojaagua-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzh9alhmlaxtIHW-gzsAsO1KrJPvxg0Ak',
    appId: '1:608499304466:android:c2f4d472e6066f4b4370cb',
    messagingSenderId: '608499304466',
    projectId: 'lojaagua-v1',
    storageBucket: 'lojaagua-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7YPK2ibn2ksh4-JeSLEMkco0wzPEtOMM',
    appId: '1:608499304466:ios:b57a411ec23eec4a4370cb',
    messagingSenderId: '608499304466',
    projectId: 'lojaagua-v1',
    storageBucket: 'lojaagua-v1.firebasestorage.app',
    iosBundleId: 'com.example.vendedorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7YPK2ibn2ksh4-JeSLEMkco0wzPEtOMM',
    appId: '1:608499304466:ios:b57a411ec23eec4a4370cb',
    messagingSenderId: '608499304466',
    projectId: 'lojaagua-v1',
    storageBucket: 'lojaagua-v1.firebasestorage.app',
    iosBundleId: 'com.example.vendedorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYzuyqjwl6dKl4oS5_VrqCHlqxuHRdXMI',
    appId: '1:608499304466:web:25a5e28dabb9c2544370cb',
    messagingSenderId: '608499304466',
    projectId: 'lojaagua-v1',
    authDomain: 'lojaagua-v1.firebaseapp.com',
    storageBucket: 'lojaagua-v1.firebasestorage.app',
  );
}
